### ISSUE TITLE
errno: 600009, errMsg: "request:fail invalid url "/costomer/getOpenId""

### ISSUE THREAD

**Issue by AnesthesiaY** [wingscloud/template-wash#14]
请问作者，点击头像登录时，控制台报错“errno: 600009, errMsg: "request:fail invalid url "/costomer/getOpenId""”，如何解决

**Comment by kieranwv** [comment]
你要接你自己的后台登录服务，这只是个前端模板

**Comment by loveOsaka** [comment]
有没有对应的后端程序推荐？
